os: osx
osx_image: xcode12.5
language: swift
script: xcodebuild clean build test -project BurgerList/BurgerList.xcodeproj -scheme "CI_macOS" CODE_SIGN_IDENTITY="" CODE_SIGNNG_REQUIRED=NO -sdk macosx -destination "platform=macOS" ONLY_ACTIVE_ARCH=YES
script: xcodebuild clean build test -project BurgerList/BurgerList.xcodeproj -scheme "CI_iOS" CODE_SIGN_IDENTITY="" CODE_SIGNNG_REQUIRED=NO -sdk iphonesimulator -destination "platform=iOS Simulator,OS=14.3,name=iPhone 8" ONLY_ACTIVE_ARCH=YES
